<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-51HLA7U" ignored="1" name="Default test(failed)" tests="2" failures="2" timestamp="14 Oct 2019 06:09:09 GMT" time="0.192" errors="0">
  <testcase name="test2" time="0.048" classname="testapp.testpage">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at testapp.testpage.test2(testpage.java:18)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.016" classname="testapp.testpage">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testapp.testpage.test3(testpage.java:24)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test1" time="0.0" classname="testapp.testpage">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
